name: run monitor

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 # schedule:
 #   - cron: "*/5 * * * *"
 # watch:
 #   types: [ started ] 


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -o app
      - name: Test
        run: go test -v ./...
      - name: Run
        run: ./app


